image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

#frontend
test-frontend-dev:
  stage: test
  image: node:8.16.0-jessie
  script:
    - cd frontend/
    - npm install --no-progress
    - npm run test
  artifacts:
    paths:
      - frontend/build/
  allow_failure: true
  only:
    - frontend-dev

test-frontend-prod:
  stage: test
  image: node:8.16.0-jessie
  script:
    - cd frontend/
    - npm install --no-progress
    - npm run test
  artifacts:
    paths:
      - frontend/build/
  only:
      - frontend-prod

deploy-frontend-dev:
  stage: deploy
  tags:
    - shell
  script:
    - cp frontend/build/ /home/beschwerdemanagement/export/dev-frontend/
  allow_failure: true
  only:
    - frontend-dev

deploy-frontend-prod:
  stage: deploy
  tags:
    - shell
  script:
    - cp frontend/build/ /home/beschwerdemanagement/export/prod-frontend/
  only:
    - frontend-prod

# backend
build-backend-dev:
  stage: build
  image: maven:3.6.1-jdk-11
  script:
    - cd backend/
    - mvn package
  artifacts:
    paths:
      - backend/target/*.jar
  allow_failure: true
  only:
    - backend-dev

build-backend-prod:
  stage: build
  image: maven:3.6.1-jdk-11
  script:
    - cd backend/
    - mvn package
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - backend-prod

deploy-backend-dev:
  stage: deploy
  tags:
    - shell
  script:
    - chmod +x backend/target/*.jar
    - cp backend/target/*.jar /home/gitlab-runner/
    - echo 'start server in background'
   #- set port
    - sudo systemctl restart stuprojavaserver
  allow_failure: true
  only:
    - backend-dev

deploy-backend-prod:
  stage: deploy
  tags:
    - shell
  script:
    - chmod +x backend/target/*.jar
    - cp backend/target/*.jar /home/gitlab-runner/
    - echo 'start server in background'
   #- set port
    - sudo systemctl restart stuprojavaserver
  only:
    - backend-prod

# all
dev:
  stage: deploy
  tags:
    - shell
  script:
    # frontend
    - cp frontend/build/ /home/beschwerdemanagement/export/development/frontend/
    # backend
    - chmod +x backend/target/*.jar
    - cp backend/target/*.jar /home/gitlab-runner/
    - echo 'start server in background'
   #- set port
    - sudo systemctl restart stuprojavaserver
  dependencies:
    - build-backend-prod
    - test-frontend-prod
  only:
    - development

master:
  stage: deploy
  tags:
    - shell
  script:
    # frontend
    - cp frontend/build/ /home/beschwerdemanagement/export/master/frontend/
    # backend
    - chmod +x backend/target/*.jar
    - cp backend/target/*.jar /home/gitlab-runner/
    - echo 'start server in background'
   #- set port
    - sudo systemctl restart stuprojavaserver
  dependencies:
    - build-backend-prod
    - test-frontend-prod
  only:
    - master
