image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy

variables:
  #DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  # backend
  D_OPTS: "-B -e -c -T 1C"

cache:
  # backend
  paths:
    - .m2/repository/
    - target/

#frontend
build-frontend-dev: &base-frontend
  stage: build
  tags:
    - shell
  script:
    - cd frontend/
    - docker build -f /home/beschwerdemanagement/docker/dockerfiles/Dockerfile_node  -t stuprommk/stupro:stupro-react .
    - buildpath=$(pwd)
    - mkdir build
    - docker run -i -v $buildpath/build:/usr/src/app/build  stuprommk/stupro:stupro-react npm run build-dev
    - sudo chown -R gitlab-runner:gitlab-runner .
  artifacts:
    paths:
      - frontend/build/
  allow_failure: false
  only:
    - frontend

build-frontend-dev-featurebranch:
  <<: *base-frontend
  allow_failure: true
  only:
    - /^frontend.+$/

build-frontend-mock:
  <<: *base-frontend
  script:
    - cd frontend/
    - docker build -f /home/beschwerdemanagement/docker/dockerfiles/Dockerfile_node  -t stuprommk/stupro:stupro-react .
    - buildpath=$(pwd)
    - mkdir mock
    - docker run -i -v $buildpath/mock:/usr/src/app/build  stuprommk/stupro:stupro-react npm run build-mock
    - sudo chown -R gitlab-runner:gitlab-runner .
  artifacts:
    paths:
      - frontend/mock/

build-frontend-mock-featurebranch:
  <<: *base-frontend
  script:
    - cd frontend/
    - docker build -f /home/beschwerdemanagement/docker/dockerfiles/Dockerfile_node  -t stuprommk/stupro:stupro-react .
    - buildpath=$(pwd)
    - mkdir mock
    - docker run -i -v $buildpath/mock:/usr/src/app/build  stuprommk/stupro:stupro-react npm run build-mock
    - sudo chown -R gitlab-runner:gitlab-runner .
  artifacts:
    paths:
      - frontend/mock/
  allow_failure: true
  only:
    - /^frontend.+$/

build-frontend-master:
  <<: *base-frontend
  script:
    - cd frontend/
    - docker build -f /home/beschwerdemanagement/docker/dockerfiles/Dockerfile_node  -t stuprommk/stupro:stupro-react .
    - buildpath=$(pwd)
    - mkdir build
    - docker run -i -v $buildpath/build:/usr/src/app/build  stuprommk/stupro:stupro-react npm run build-prod
    - sudo chown -R gitlab-runner:gitlab-runner .
  allow_failure: false
  only:
    - master

test-frontend:
  stage: test
  tags:
    - shell
  script:
    - echo 'no tests'
  artifacts:
    paths:
      - frontend/build/
      - frontend/mock/
  allow_failure: false
  only:
    - /^frontend.*$/
    - master

deploy-frontend-mock:
  stage: deploy
  tags:
    - shell
  script:
    - cp -r frontend/mock/* /home/beschwerdemanagement/export/live/frontend_mock/
    - echo 'rollback data'
    - mkdir                  /home/beschwerdemanagement/export/rollback/frontend/frontend_mock_$CI_COMMIT_SHA
    - cp -r frontend/mock/*  /home/beschwerdemanagement/export/rollback/frontend/frontend_mock_$CI_COMMIT_SHA
  allow_failure: false
  only:
    - frontend

deploy-frontend-dev:
  stage: deploy
  tags:
    - shell
  script:
    - cp -r frontend/build/* /home/beschwerdemanagement/export/live/frontend_dev/
    - echo 'rollback data'
    - mkdir                  /home/beschwerdemanagement/export/rollback/frontend/frontend_dev_$CI_COMMIT_SHA
    - cp -r frontend/build/* /home/beschwerdemanagement/export/rollback/frontend/frontend_dev_$CI_COMMIT_SHA
  allow_failure: true
  only:
    - frontend

# python
build-python:
  stage: build
  image: python
  script:
    - cd python/
    - pip3 install pipenv --user
    - pip3 install flake8 --user
    - ~/.local/bin/pipenv install
    - ~/.local/bin/flake8 --ignore E501 .
    - echo "DEPLOY=True" > .env
  artifacts:
    paths:
      - python/
  only:
    - /^python.*$/

test-python:
  stage: test
  tags:
    - shell
  script:
    - echo 'no tests'
  artifacts:
    paths:
      - python/
  only:
    - /^python.*$/

deploy-python:
  stage: deploy
  tags:
    - shell
  script:
    # copy python to destination and systemd script
    - chmod -R +rw python/
    - cp -r python/* /home/beschwerdemanagement/export/live/python_dev/
    - echo 'rollback data'
    - mkdir          /home/beschwerdemanagement/export/rollback/python/python_dev_$CI_COMMIT_SHA
    - cp -r python/* /home/beschwerdemanagement/export/rollback/python/python_dev_$CI_COMMIT_SHA
    - sudo systemctl restart stupropython_dev
  only:
    - /^python.*$/

# backend
build-backend-dev: &base-backend
  stage: build
  tags:
    - shell
  script:
    - cd backend/
    - mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-surefire-plugin:2.22.2
    - echo 'build'
    - mvn $D_OPTS package -Dmaven.test.skip=true
  artifacts:
    paths:
      - backend/target/*.jar
      - backend/doc/openapi.yaml
  allow_failure: false
  only:
    - backend

build-backend-dev-featurebranch:
  <<: *base-backend
  allow_failure: true
  only:
    - /^backend.+$/

build-backend-master:
  <<: *base-backend
  allow_failure: false
  only:
    - master

test-backend-dev:
  <<: *base-backend
  stage: test
  script:
    - cd backend/
    - mvn $D_OPTS test
  only:
    - backend
    - master

test-backend-dev-featurebranch:
  <<: *base-backend
  stage: test
  script:
    - cd backend/
    - mvn $D_OPTS test
  allow_failure: true
  only:
    - /^backend.+$/

deploy-backend-dev:
  stage: deploy
  tags:
    - shell
  script:
    - chmod +x backend/target/*.jar
    - cp -r backend/target/*.jar /home/beschwerdemanagement/export/live/backend_dev/
    - echo 'rollback data'
    - mkdir                      /home/beschwerdemanagement/export/rollback/backend/backend_dev_$CI_COMMIT_SHA
    - cp -r backend/target/*.jar /home/beschwerdemanagement/export/rollback/backend/backend_dev_$CI_COMMIT_SHA
    - echo 'start server in background'
    - sudo systemctl restart stuprojavaserver_dev
    - echo 'copy current openapi to destination'
    - chmod +rx backend/doc/openapi.yaml
    - sudo cp backend/doc/openapi.yaml /home/beschwerdemanagement/export/data/
  allow_failure: false
  only:
    - backend

# all
master:
  stage: deploy
  tags:
    - shell
  script:
    # frontend
    - chmod -R +rw frontend/build/
    - cp -r frontend/build/* /home/beschwerdemanagement/export/master/frontend/
    # backend
    - chmod +x backend/target/*.jar
    - cp -r backend/target/*.jar /home/beschwerdemanagement/export/live/master/backend/
    - echo 'rollback data'
    - mkdir                      /home/beschwerdemanagement/export/rollback/backend/backend_master_$CI_COMMIT_SHA
    - cp -r backend/target/*.jar /home/beschwerdemanagement/export/rollback/backend/backend_master_$CI_COMMIT_SHA
    - echo 'start server in background'
    - sudo systemctl restart stuprojavaserver
  only:
    - master
