# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/api/import/text
Content-Type: application/json

{
  "text": "Das ist ein Beispiel Text"
}

###

GET http://localhost:8080/api/complaints/0

###

DELETE http://localhost:8080/api/complaints/0

###

POST http://localhost:8080/api/import/text
Content-Type: application/json

{
"text" : "ausfall und fahrer unfreundlich"
}

###

POST https://kikuko.iao.fraunhofer.de/apitext

###

POST http://localhost:8080/api/import/text
Content-Type: application/json

{
  "text": "Fahrer ist leider nicht erfolgt!"
}

###

POST http://localhost:8080/api/responses/new/11

###

DELETE http://localhost:8080/api/templates/8

###

# Returns all complaints in the database
GET https://beschwerdemanagement-dev.iao.fraunhofer.de/api/complaints

###

# Posts a new complaint text into the database
POST https://beschwerdemanagement-dev.iao.fraunhofer.de/api/import/text
Content-Type: application/json

{
  "text": "Fahrt ist leider nicht erfolgt!\nDas ist sehr schade!\nLiebe Grüße\nMax Mustermann"
}

###

# get a single complaint
GET https://beschwerdemanagement-dev.iao.fraunhofer.de/api/complaints/68

###

# delete a complaint
DELETE https://beschwerdemanagement-dev.iao.fraunhofer.de/api/complaints/68

###

