# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/api/complaints/import
Content-Type: application/json

{
  "text": "Der Fahrer war sehr unfreundlich!\nIch bitte um Rückerstattung von 23,12€."
}

###

GET http://localhost:8080/api/responses/plain/14

###

POST http://localhost:8080/api/templates
Content-Type: application/json

{
  "componentName": "Begrüßung_Morgens_OhneName",
  "priority": 100,
  "rulesXml": "<And><PredecessorCount min=\"1\"/><Subject value=\"Fahrer unfreundlich\"/><Sentiment value=\"Wut\"/></And>",
  "templateTexts": [
    "Guten Morgen,",
    "Guten Tag,"
  ]
}

###

DELETE http://localhost:8080/api/templates/1

###

DELETE http://localhost:8080/api/complaints/all

###

GET https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/templates

###

DELETE https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/templates/all

###

GET https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/responses/1

###

DELETE http://localhost:8080/api/complaints/1

###

POST http://localhost:8080/api/complaints/import
Content-Type: application/json

{
  "text": "Hallo, meine Fahrt ist leider nicht erfolgt! Das ist sehr schade! Liebe Grüße, Max Mustermann. Auf Wiedersehen!"
}



###

POST https://kikuko.iao.fraunhofer.de/apitext

###

POST http://localhost:8080/api/complaints/import
Content-Type: application/json

{
  "text": "Der Fahrer war sehr unfreundlich!"
}

###

GET http://localhost:8080/api/stats/tagcloud?words_only=true&subject=Sonstiges,Fahrt nicht erfolgt

###

GET http://localhost:8080/api/complaints?sort_by=priority_desc
###

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/templates
Content-Type: application/json

{
  "templateText": "Guten Tag!\n\nEs tut uns sehr leid, dass Sie mit uns unzufrieden sind.",
  "responsePart": "Begrüßung",
  "successorParts": [
    "Datumsangabe"
  ],
  "subject": null
}

###

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/templates
Content-Type: application/json

{
  "templateText": "Ihre Beschwerde ist am ${upload_date} um ${upload_time} bei uns eingegangen.",
  "responsePart": "Datumsangabe",
  "successorParts": [
    "Verabschiedung"
  ],
  "subject": null
}

###

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/templates
Content-Type: application/json

{
  "templateText": "\n\nMit freundlichen Grüßen\n\nIhr Beschwerdebot",
  "responsePart": "Verabschiedung",
  "successorParts": [
  ],
  "subject": null
}

###

DELETE http://localhost:8080/api/templates/10

###

# Returns all complaints in the database
GET https://beschwerdemanagement-dev.iao.fraunhofer.de/api/complaints

###

# Posts a new complaint text into the database
POST https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/complaints/import
Content-Type: application/json

{
  "text": "Fahrt ist leider nicht erfolgt!"
}

###

# get a single complaint
GET https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/84

###

# delete a complaint
DELETE https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/complaints/all

### Antwortgenerierungs-Beispiele

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/complaints/import
Content-Type: application/json

{
  "text": "Hallo, meine Fahrt ist leider nicht erfolgt! Das ist sehr schade! Liebe Grüße, Max Mustermann. Auf Wiedersehen!"
}

###

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/new/4

###

GET https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/responses/5

###

DELETE https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/73

###

GET https://beschwerdemanagement-dev.iao.fraunhofer.de/dev/api/stats/tagcloud

###