# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/api/import/text
Content-Type: application/json

{
  "text": "Das ist ein Beispiel Text"
}

###

GET http://localhost:8080/api/complaints/0

###

DELETE http://localhost:8080/api/complaints/0

###

POST http://localhost:8080/api/import/text
Content-Type: application/json

{
"text" : "ausfall abicbai unfreundlich"
}

###

POST https://kikuko.iao.fraunhofer.de/apitext

###

POST http://localhost:8080/api/import/text
Content-Type: application/json

{
  "text": "Der Fahrer war sehr unfreundlich!"
}

###

POST http://localhost:8080/api/responses/new/20

###

DELETE http://localhost:8080/api/templates/8

###

GET http://localhost:8080/api/responses/24

### Antwortgenerierungs-Beispiele

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/api/import/text
Content-Type: application/json

{
  "text": "Hallo! Der Fahrer war heute sehr unfreundlich!"
}

###

POST https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/new/72

###

GET https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/73

###

DELETE https://beschwerdemanagement-dev.iao.fraunhofer.de/api/responses/73

###