# This document contains sample HTTP request which can be executed with IntelliJ idea.

# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# POST request for issue #2785 Erster Integrationstest
POST http://localhost:8080/api/test/recognizer
Content-Type: application/json
Accept: application/json

{
  "text": "Die Buslinie 637 ist am 01.03.2019 an der Gartenheimstraße in Langenberg(Schule!) um 13:46 nicht gekommen."
}


###

# POST request for issue #2786 Einbindung eines externen Extraktors
POST http://localhost:8080/api/test/textominado
Content-Type: application/json
Accept: application/json

{
  "text": "Weil mein Bus zu spät war musste ich 23,70 € für das Taxi bezahlen, die will ich zurück haben"
}

###

# POST request for issue #2787 Stapelverarbeitung
POST http://localhost:8080/api/test/textominado
Content-Type: multipart/form-data; boundary=----------287032381131322
Accept: application/json

------------287032381131322
Content-Disposition: form-data; name="datafile3"; filename="C:/Users/PaBre/Documents/Test.txt"
Content-Type: text/plain

GIF87a.............,...........D..;
------------287032381131322--

###

# Test request for textominado
POST https://textominado.iao.fraunhofer.de/backend/entity-recognition/money-amount
Content-Type: application/json
Authorization: Basic dGV4dG9taW5hZG86VGVhbVBhc3MyMDE4IQ==

{
  "text": "Weil mein Bus zu spät war musste ich 23,70 € für das Taxi bezahlen, die will ich zurück haben",
  "textID": "1",
  "language": "de"
}

###
