openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: "https://querimonia.iao.fraunhofer.de/python"
paths:
  /emotion_analyse:
    post:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: String
      responses:
        200:
          description: OK

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: [
  ]